version: '3.8'

services:
  webapp:
    image: kanban-webapp:latest
    build:
      context: ./ui
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s