name: Build UI

on:
  [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: ./ui
      run: npm install

    - name: Build Vite app
      working-directory: ./ui
      run: npm run build

    - name: Upload production-ready build
      uses: actions/upload-artifact@v3
      with:
        name: vite-build
        path: ui/dist 

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy to s3
      run:
        aws s3 sync ui/dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}
