name: Run E2E Tests

on:
  [workflow_dispatch]
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: pull Docker image
        run: docker pull ghcr.io/landot/kanban-e2e-test:latest

      - name: Run tests
        run: |
          docker run -e BASE_URL=kanban.timlandowski.com ghcr.io/landot/kanban-e2e-test:latest
