name: Run E2E Tests

on:
  workflow_dispatch:
    inputs:
      BASE_URL:
        description: 'The base URL for the application'
        required: false
        default: 'https://kanban.timlandowski.com/'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: |
          docker run -e BASE_URL=${{ github.event.inputs.BASE_URL }} ghcr.io/landot/kanban-e2e-test:main
