name: Sync s3 Bucket
on:
  [workflow_dispatch]
jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-2
        - name: Copy files to the s3 website content bucket
          run:
            aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest